---
title: "Trabajo_Montoya_Arcuschin"
author: "Melody Sol Arcuschin y Vitor Montoya"
date: "2024-06-17"
output: html_document
---

Librerías y lectura de documentos
```{r}
library(tidyverse)
library(haven)
library(openxlsx)
library(kableExtra)


setwd("C:/Users/melod/Escritorio/Estudio/Posgrado/2024/Mercado de trabajo/Evaluación/Evaluacion/")
bolivia<- readRDS("Bolivia_1a4T2019.RDS")
chile <- read.csv2("Chile_2019.csv")
```

Bolivia-Observación
```{r}
View(encuestas_b)
colnames(encuestas_b)
```

Bolivia-Indicadores
```{r}
suma_pea <- sum(bolivia$fact_mes[bolivia$pea == 1], na.rm = TRUE)
suma_desocupados <- sum(bolivia$fact_mes[bolivia$pead == 1], na.rm = TRUE)
suma_ocupados <- sum(bolivia$fact_mes[bolivia$peao == 1], na.rm = TRUE)
suma_total <- sum(bolivia$fact_mes)
informales <- sum(bolivia$fact_mes[bolivia$s2_26 <= 4], na.rm = TRUE)
asalariados <- sum(bolivia$fact_mes[bolivia$s2_17a == 2], na.rm = TRUE)
asalariados_precarios <- sum(bolivia$fact_mes[(bolivia$s2_21 %in% c(2,3, 5)) | (bolivia$s2_21a != 3)], na.rm = TRUE)
TA_B = suma_pea/suma_total
TD_B = suma_desocupados/suma_pea
TI_B = informales/suma_ocupados
TP_B = asalariados_precarios/asalariados
```

Chile-Observación
```{r}
chile %>% count(grupo_edad, wt=fact_cal_esi) %>% mutate(porcentaje =round((n/sum(n)*100), digits = 1))
```

Chile-Indicadores
```{r}
```

